### PR TITLE
Configure user workload monitoring defaults

### PR DESCRIPTION
**Pull request by srueg**
## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the documentation.
- [x] Update the ./CHANGELOG.md.

### CODE REVIEW

**Review by corvus-ch — APPROVED** [review]
Our style guide states to directly expose the `spec` field of a CRD. This is to prevent us from changing the component fore each and every change of such a CRD.

Here we are dealing with a ConfigMap but we should still apply the same principle. Feel free to change accordingly or create a ticket to have this changed.

**Comment by srueg** [comment]
Hmm good point. But exposing the config map would require specifying strings which can't be merged properly via the hierarchy. I guess it goes into the category of the following, no?
> Try to avoid exposing non-mergeable data (like strings) directly in the hierarchy. Consider implementing rendering structured data into string format when the component is compiled.

https://syn.tools/syn/explanations/jsonnet.html#_merging_external_config_data

**Comment by corvus-ch** [comment]
Why? A ConfigMap is a dictionary structure and can be merged by definition. The quoted sentence from the style guide is targeting config files that are represented as strings within yaml. See https://github.com/projectsyn/component-fluentbit for an example of where that rule applies.

**Comment by corvus-ch** [comment]
Never mind. I was missing one level of keys within the parameter defaults. It already following that rule.

**Pull request merged**
