### PR TITLE
Remove cluster logging prometheus rules

### PR DESCRIPTION
**Pull request by DebakelOrakel**
Prometheus rules for cluster logging are added to the openshift4-logging component.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the documentation.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [ ] Link this PR to related issues.

### CODE REVIEW

**Comment by DebakelOrakel** [comment]
Is a reduction in functionality an enhancement 🤔

**Review by simu — APPROVED** [review]
LGTM. Please rebase your branch to a single commit before merging.

**Comment by DebakelOrakel** [comment]
> 
> 
> LGTM. Please rebase your branch to a single commit before merging.
> 
> Edit: I'd vote for labeling this PR as `change`.

Hmm, there's no change label in this project.

**Comment by simu** [comment]
> > LGTM. Please rebase your branch to a single commit before merging.
> > Edit: I'd vote for labeling this PR as `change`.
> 
> Hmm, there's no change label in this project.

Now there is ;)

**Review by megian — APPROVED** [review]

**Pull request merged**
